// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvHkRwgCEvaCY2s5PodR3kDtX7nNTl1uw',
    appId: '1:391534008822:web:6ed7346cdc34e18cdbcfd7',
    messagingSenderId: '391534008822',
    projectId: 'fuel-tracker-app-4a4c5',
    authDomain: 'fuel-tracker-app-4a4c5.firebaseapp.com',
    storageBucket: 'fuel-tracker-app-4a4c5.firebasestorage.app',
    measurementId: 'G-SHVFYHZV3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXGpjdAj8T5wEFmGL2HM9IC8SQlHpm7OU',
    appId: '1:391534008822:android:29245e1a0be59498dbcfd7',
    messagingSenderId: '391534008822',
    projectId: 'fuel-tracker-app-4a4c5',
    storageBucket: 'fuel-tracker-app-4a4c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMPpPxGWG35wFdnpiBjSvh0lD-JSdOzcA',
    appId: '1:391534008822:ios:b0c16c06189f98f3dbcfd7',
    messagingSenderId: '391534008822',
    projectId: 'fuel-tracker-app-4a4c5',
    storageBucket: 'fuel-tracker-app-4a4c5.firebasestorage.app',
    iosBundleId: 'br.com.fuelTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMPpPxGWG35wFdnpiBjSvh0lD-JSdOzcA',
    appId: '1:391534008822:ios:b0c16c06189f98f3dbcfd7',
    messagingSenderId: '391534008822',
    projectId: 'fuel-tracker-app-4a4c5',
    storageBucket: 'fuel-tracker-app-4a4c5.firebasestorage.app',
    iosBundleId: 'br.com.fuelTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvHkRwgCEvaCY2s5PodR3kDtX7nNTl1uw',
    appId: '1:391534008822:web:646ded1ff5f15578dbcfd7',
    messagingSenderId: '391534008822',
    projectId: 'fuel-tracker-app-4a4c5',
    authDomain: 'fuel-tracker-app-4a4c5.firebaseapp.com',
    storageBucket: 'fuel-tracker-app-4a4c5.firebasestorage.app',
    measurementId: 'G-25ECQY880C',
  );
}
